# Generated by Django 5.2.3 on 2025-06-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("subcontractors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("INVITATION", "Tender Invitation"),
                            ("REMINDER", "Deadline Reminder"),
                            ("ADDENDUM", "Tender Addendum"),
                            ("OTHER", "Other Communication"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="projects.project",
                    ),
                ),
                (
                    "subcontractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="subcontractors.subcontractor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailMonitorConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder_name",
                    models.CharField(
                        help_text="Name of folder in Outlook to monitor", max_length=255
                    ),
                ),
                (
                    "folder_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the folder in Outlook",
                        max_length=255,
                    ),
                ),
                ("last_check_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_config",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
