# Generated by Django 5.2.3 on 2025-06-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "sharepoint_folder_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_folder_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_folder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_date", models.DateField()),
                ("tender_deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LIVE", "Live"),
                            ("SUBMITTED", "Submitted"),
                            ("SUCCESSFUL", "Successful"),
                            ("UNSUCCESSFUL", "Unsuccessful"),
                            ("DECLINED", "Declined"),
                            ("NEXT_STAGE", "Next Stage"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="LIVE",
                        max_length=20,
                    ),
                ),
                ("estimator", models.CharField(blank=True, max_length=50)),
                ("project_manager", models.CharField(blank=True, max_length=50)),
                ("pmqs", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "contract_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("win_room_date", models.DateField(blank=True, null=True)),
                ("rfi_deadline", models.DateField(blank=True, null=True)),
                ("site_visit_date", models.DateField(blank=True, null=True)),
                ("sc_deadline", models.DateField(blank=True, null=True)),
                ("mid_bid_review_date", models.DateField(blank=True, null=True)),
                (
                    "tender_bid_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "margin_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("key_risks", models.TextField(blank=True)),
                (
                    "sharepoint_folder_url",
                    models.URLField(
                        blank=True,
                        help_text="SharePoint link to the ITT (Invitation to Tender) documents folder",
                        null=True,
                    ),
                ),
                (
                    "sharepoint_link_description",
                    models.CharField(
                        blank=True,
                        default="ITT Documents",
                        help_text="Description for the SharePoint link (e.g., 'ITT Documents', 'Tender Package')",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
