# Generated by Django 5.2.3 on 2025-06-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("subcontractors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("answer_text", models.TextField(blank=True)),
                ("asked_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_questions",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RFIItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("question", models.TextField()),
                ("response", models.TextField(blank=True)),
                ("contractor_response", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ANSWERED", "Answered"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfi_items",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenderAddendum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_by", models.CharField(blank=True, max_length=100)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tender_addenda",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenderAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                ("project_overview", models.TextField(blank=True)),
                ("key_requirements", models.JSONField(default=list)),
                ("scope_of_work", models.TextField(blank=True)),
                ("technical_specifications", models.JSONField(default=dict)),
                ("identified_risks", models.JSONField(default=list)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("estimated_value_range", models.JSONField(default=dict)),
                ("cost_breakdown", models.JSONField(default=dict)),
                ("project_duration_weeks", models.IntegerField(blank=True, null=True)),
                ("critical_milestones", models.JSONField(default=list)),
                ("building_standards", models.JSONField(default=list)),
                ("environmental_requirements", models.TextField(blank=True)),
                ("health_safety_requirements", models.TextField(blank=True)),
                ("documents_analyzed", models.JSONField(default=list)),
                ("analysis_confidence", models.FloatField(default=0.0)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tender_analysis",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("TENDER", "Tender Document"),
                            ("DRAWING", "Drawing"),
                            ("SPECIFICATION", "Specification"),
                            ("CONTRACT", "Contract Document"),
                            ("OTHER", "Other"),
                        ],
                        default="TENDER",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="tender_documents/%Y/%m/")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tender_documents",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenderQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TECHNICAL", "Technical"),
                            ("COMMERCIAL", "Commercial"),
                            ("PROGRAM", "Program"),
                            ("RISK", "Risk"),
                            ("COMPLIANCE", "Compliance"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High Priority"),
                            ("MEDIUM", "Medium Priority"),
                            ("LOW", "Low Priority"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("is_answered", models.BooleanField(default=False)),
                ("answer_text", models.TextField(blank=True)),
                ("answered_by", models.CharField(blank=True, max_length=100)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tender_questions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenderInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Response"),
                            ("ACCEPTED", "Will Tender"),
                            ("DECLINED", "Will Not Tender"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("email_sent", models.DateTimeField(blank=True, null=True)),
                ("email_opened", models.BooleanField(default=False)),
                ("email_opened_at", models.DateTimeField(blank=True, null=True)),
                ("documents_downloaded", models.BooleanField(default=False)),
                (
                    "documents_downloaded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                ("sent_by", models.CharField(blank=True, max_length=100)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("custom_message", models.TextField(blank=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about communication with this subcontractor",
                    ),
                ),
                (
                    "tender_returned",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the subcontractor has returned their tender",
                    ),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, help_text="When the tender was returned", null=True
                    ),
                ),
                (
                    "tender_attachments",
                    models.JSONField(
                        blank=True,
                        help_text="Information about returned tender attachments",
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="projects.project",
                    ),
                ),
                (
                    "subcontractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tender_invitations",
                        to="subcontractors.subcontractor",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "subcontractor")},
            },
        ),
    ]
