# Generated by Django 5.2.3 on 2025-07-03 20:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("tenders", "0003_alter_tenderanalysis_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="AI Conversation", max_length=200)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "tenders_ai_conversation",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="AIQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("answer_text", models.TextField()),
                (
                    "confidence_score",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("source_documents", models.JSONField(blank=True, default=list)),
                ("document_references", models.JSONField(blank=True, default=list)),
                ("analysis_metadata", models.JSONField(blank=True, default=dict)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_questions",
                        to="tenders.aiconversation",
                    ),
                ),
            ],
            options={
                "db_table": "tenders_ai_question",
                "ordering": ["-created_date"],
            },
        ),
    ]
