# Generated by Django 5.2.3 on 2025-07-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0004_aiconversation_aiquestion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenderanalysis",
            name="compliance_requirements",
        ),
        migrations.AddField(
            model_name="tenderanalysis",
            name="building_standards",
            field=models.JSONField(
                default=list,
                help_text="List of building standards, codes, and regulatory requirements",
            ),
        ),
        migrations.AddField(
            model_name="tenderanalysis",
            name="environmental_requirements",
            field=models.TextField(
                blank=True,
                help_text="Environmental compliance requirements and standards",
            ),
        ),
        migrations.AddField(
            model_name="tenderanalysis",
            name="health_safety_requirements",
            field=models.TextField(
                blank=True,
                help_text="Comprehensive health and safety requirements and CDM regulations",
            ),
        ),
    ]
