# Generated by Django 5.2.3 on 2025-07-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0005_remove_tenderanalysis_compliance_requirements_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenderanalysis",
            name="handover_date",
        ),
        migrations.RemoveField(
            model_name="tenderanalysis",
            name="insurance_requirements",
        ),
        migrations.RemoveField(
            model_name="tenderanalysis",
            name="key_opportunities",
        ),
        migrations.RemoveField(
            model_name="tenderanalysis",
            name="liquidated_damages",
        ),
        migrations.RemoveField(
            model_name="tenderanalysis",
            name="payment_terms",
        ),
        migrations.RemoveField(
            model_name="tenderanalysis",
            name="possession_date",
        ),
        migrations.RemoveField(
            model_name="tenderanalysis",
            name="practical_completion_date",
        ),
        migrations.RemoveField(
            model_name="tenderanalysis",
            name="start_on_site_date",
        ),
        migrations.RemoveField(
            model_name="tenderanalysis",
            name="timeline_analysis",
        ),
        migrations.RemoveField(
            model_name="tenderanalysis",
            name="value_range_max",
        ),
        migrations.RemoveField(
            model_name="tenderanalysis",
            name="value_range_min",
        ),
        migrations.AddField(
            model_name="tenderanalysis",
            name="compliance_requirements",
            field=models.JSONField(
                default=list,
                help_text="List of compliance requirements including regulations and standards",
            ),
        ),
        migrations.AddField(
            model_name="tenderanalysis",
            name="cost_breakdown",
            field=models.JSONField(
                default=dict, help_text="Detailed cost breakdown by trade/category"
            ),
        ),
        migrations.AddField(
            model_name="tenderanalysis",
            name="estimated_value_range",
            field=models.JSONField(
                default=dict,
                help_text="Dictionary containing min/max estimated project values",
            ),
        ),
        migrations.AlterField(
            model_name="tenderanalysis",
            name="budget_estimates",
            field=models.TextField(
                blank=True, help_text="Budget estimates and financial analysis summary"
            ),
        ),
        migrations.AlterField(
            model_name="tenderanalysis",
            name="contract_information",
            field=models.JSONField(
                default=dict,
                help_text="Contract details including type, terms, and conditions",
            ),
        ),
        migrations.AlterField(
            model_name="tenderanalysis",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("JCT_STANDARD", "JCT Standard Building Contract"),
                    ("JCT_DESIGN_BUILD", "JCT Design and Build Contract"),
                    ("JCT_MINOR_WORKS", "JCT Minor Works Contract"),
                    ("NEC4", "NEC4 Engineering and Construction Contract"),
                    ("FIDIC", "FIDIC Conditions of Contract"),
                    ("BESPOKE", "Bespoke Contract"),
                    ("OTHER", "Other"),
                ],
                help_text="Type of construction contract",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tenderanalysis",
            name="critical_milestones",
            field=models.JSONField(
                default=list, help_text="List of critical project milestones and dates"
            ),
        ),
        migrations.AlterField(
            model_name="tenderanalysis",
            name="estimated_project_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Single estimated project value",
                max_digits=12,
                null=True,
            ),
        ),
    ]
