# Generated by Django 5.2.3 on 2025-07-14 06:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0006_remove_tenderanalysis_handover_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rfiitem",
            options={
                "ordering": ["priority", "category", "created_at"],
                "verbose_name": "RFI Item",
                "verbose_name_plural": "RFI Items",
            },
        ),
        migrations.RemoveField(
            model_name="rfiitem",
            name="contractor_response",
        ),
        migrations.RemoveField(
            model_name="rfiitem",
            name="response",
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="assigned_to",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="client_response",
            field=models.TextField(
                blank=True, help_text="Client's response to the RFI"
            ),
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="context",
            field=models.TextField(
                blank=True, help_text="Additional context for the question"
            ),
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="created_by",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="document_reference",
            field=models.CharField(
                blank=True, help_text="Reference to source document", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="internal_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes about the RFI"
            ),
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="location_in_document",
            field=models.CharField(
                blank=True, help_text="Page/section reference", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="pricing_impact",
            field=models.CharField(
                choices=[
                    ("HIGH", "High - Significant cost impact"),
                    ("MEDIUM", "Medium - Moderate cost impact"),
                    ("LOW", "Low - Minor cost impact"),
                    ("NONE", "No cost impact"),
                ],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="rfi_number",
            field=models.CharField(
                blank=True, help_text="Auto-generated RFI number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="risk_if_unresolved",
            field=models.TextField(
                blank=True, help_text="Risk if question remains unanswered"
            ),
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfiitem",
            name="tender_analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rfi_items",
                to="tenders.tenderanalysis",
            ),
        ),
        migrations.AlterField(
            model_name="rfiitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("TECHNICAL", "Technical Specifications"),
                    ("COMMERCIAL", "Commercial Terms"),
                    ("PROGRAMME", "Programme & Timeline"),
                    ("SPECIFICATION", "Material Specifications"),
                    ("DRAWING", "Drawing Clarifications"),
                    ("HEALTH_SAFETY", "Health & Safety"),
                    ("ENVIRONMENTAL", "Environmental Requirements"),
                    ("QUALITY", "Quality Standards"),
                    ("SCOPE", "Scope Boundaries"),
                    ("ACCESS", "Site Access & Logistics"),
                    ("COORDINATION", "Trade Coordination"),
                    ("EXCLUSIONS", "Scope Exclusions"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rfiitem",
            name="priority",
            field=models.CharField(
                choices=[
                    ("CRITICAL", "Critical - Affects bid validity"),
                    ("HIGH", "High - Affects pricing accuracy"),
                    ("MEDIUM", "Medium - Affects risk assessment"),
                    ("LOW", "Low - Minor clarification"),
                ],
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="rfiitem",
            name="question",
            field=models.TextField(
                help_text="Clear, specific question requiring clarification"
            ),
        ),
        migrations.AlterField(
            model_name="rfiitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Response"),
                    ("SUBMITTED", "Submitted to Client"),
                    ("RESPONDED", "Client Responded"),
                    ("CLARIFIED", "Clarified & Resolved"),
                    ("WITHDRAWN", "Question Withdrawn"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="rfiitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
