# Generated by Django 5.2.3 on 2025-07-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0007_alter_rfiitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenderinvitation",
            name="last_pending_reminder",
            field=models.DateTimeField(
                blank=True, help_text="Last time pending reminder was sent", null=True
            ),
        ),
        migrations.AddField(
            model_name="tenderinvitation",
            name="last_will_tender_reminder",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time will tender reminder was sent",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenderinvitation",
            name="pending_reminder_count",
            field=models.IntegerField(
                default=0, help_text="Number of pending reminders sent"
            ),
        ),
        migrations.AddField(
            model_name="tenderinvitation",
            name="will_tender_reminder_count",
            field=models.IntegerField(
                default=0, help_text="Number of will tender reminders sent"
            ),
        ),
    ]
