# Generated by Django 5.2.3 on 2025-06-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("subcontractors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubcontractorFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comparison_data",
                    models.JSONField(
                        blank=True,
                        help_text="Extracted comparison data for this subcontractor",
                        null=True,
                    ),
                ),
                (
                    "spreadsheet_path",
                    models.CharField(
                        help_text="Path to the comparison spreadsheet", max_length=255
                    ),
                ),
                (
                    "trade",
                    models.CharField(
                        help_text="Trade from the comparison spreadsheet",
                        max_length=100,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("email_subject", models.CharField(blank=True, max_length=255)),
                ("email_body", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontractor_feedback",
                        to="projects.project",
                    ),
                ),
                (
                    "subcontractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="subcontractors.subcontractor",
                    ),
                ),
            ],
        ),
    ]
