# Generated by Django 5.2.3 on 2025-06-25 10:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subcontractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("head_office", models.CharField(max_length=255)),
                (
                    "pqq_status",
                    models.CharField(
                        choices=[
                            ("NONE", "Not Started"),
                            ("SENT", "Sent"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("surname", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "subcontractor_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("landline", models.CharField(blank=True, max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("meeting_booked", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "regions",
                    models.ManyToManyField(blank=True, to="subcontractors.region"),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontractors",
                        to="subcontractors.trade",
                    ),
                ),
            ],
            options={
                "ordering": ["company", "trade"],
                "unique_together": {("company", "head_office")},
            },
        ),
    ]
