# Generated by Django 5.2.3 on 2025-07-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subcontractors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcontractor",
            name="email",
            field=models.TextField(
                help_text="Enter multiple email addresses separated by semicolons (;)"
            ),
        ),
    ]
