# Generated by Django 5.2.3 on 2025-06-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Project Statuses",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_number", models.CharField(max_length=20, unique=True)),
                ("estimator", models.CharField(max_length=50)),
                ("client", models.CharField(max_length=255)),
                ("project_name", models.CharField(max_length=255)),
                ("pmqs", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "contract_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("location", models.CharField(max_length=255)),
                ("date_received", models.DateField(blank=True, null=True)),
                ("win_room_date", models.DateField(blank=True, null=True)),
                ("rfi_deadline", models.DateField(blank=True, null=True)),
                ("site_visit_date", models.DateField(blank=True, null=True)),
                ("sc_deadline", models.DateField(blank=True, null=True)),
                ("tender_deadline", models.DateTimeField(blank=True, null=True)),
                ("mid_bid_review_date", models.DateField(blank=True, null=True)),
                (
                    "tender_bid_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "margin_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("key_risks", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="project_tracker.projectstatus",
                    ),
                ),
            ],
        ),
    ]
